### ISSUE TITLE
Guessing a word with a repeating letter will cause all instances of that letter to turn yellow, even if the letter appears only once in the answer

### ISSUE THREAD

**Issue by JamesL813** [ivanjermakov/wordle#11]
For example, if the answer is "apple" and I guess "panda", both "a"s will be yellow rather than just one instance. Also if the word is "apple" and I guess "aroma" the first "a" will be green and the second "a" will be yellow.

Both of these scenarios could lead people to believe there's more than one of a certain letter when there isn't

**Comment by ivanjermakov** [comment]
Yes, I'm aware of this bug. Second case is obvious, but regarding the first one, what would official Wordle show in this case?

**Comment by JamesL813** [comment]
It would highlight the first instance of the letter or the first n instances if the letter appears n times

**Comment by ivanjermakov** [comment]
Will keep it there as a test case
![image](https://user-images.githubusercontent.com/26609879/152675413-0f09197b-f3e8-444a-942b-87d2f4ccffdc.png)
